spring:
  application.version: @pom.version@

server:
  port: 8080

management.contextPath: /admin

# Custom actuators
exception.interceptor.queue.size: 50
exception.interceptor.endpoint: exceptions
exception.interceptor.stacktrace: false
trace.interceptor.queue.size: 50
trace.interceptor.endpoint: requests

# Properties used by /admin/info and /admin/build endpoints.
info.app.name: ${spring.application.name}
info.app.profile: ${spring.profiles.active}
info.app.maven.version: @pom.version@
info.app.maven.artifactId: @pom.artifactId@
info.app.maven.groupId: @pom.groupId@
info.app.ci.build: @ci.build@
info.app.ci.url: @pom.ciManagement.url@

---
spring:
  profiles: development


---
spring:
   profiles: test


---
spring:
   profiles: production






